// Estilos compartilhados da tela home e das abas.
// Extraido do home.tsx para que os componentes de aba (FixoTab, VariavelTab,
// CartaoTab) usem exatamente as mesmas definicoes, sem duplicacao.

import { Platform, StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safeArea: { flex: 1 },
  loadingWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12, padding: 24 },
  loadingText: { fontSize: 16, fontWeight: '700' },
  scrollContent: { paddingHorizontal: 16, paddingTop: 14 },
  topRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 },
  topActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  avatar: { width: 48, height: 48, borderRadius: 999, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5 },
  eyebrow: { fontSize: 11, fontWeight: '800', letterSpacing: 1.4, textTransform: 'uppercase', marginBottom: 8, textAlign: 'center' },
  title: { fontSize: 27, fontWeight: '800', textAlign: 'center', letterSpacing: -0.6 },
  subtitle: { fontSize: 13, lineHeight: 19, textAlign: 'center', marginTop: 5, marginBottom: 16, fontWeight: '500' },
  selectorGroup: { flexDirection: 'row', gap: 10, marginBottom: 12 },
  salaryInput: { minWidth: 180, fontSize: 29, fontWeight: '800', textAlign: 'center', paddingVertical: 0, letterSpacing: -1 },
  summaryRow: { flexDirection: 'row', gap: 10, marginBottom: 18 },
  summaryCard: { flex: 1, minWidth: '47%', borderRadius: 20, padding: 14, borderWidth: 1 },
  smallLabel: { fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1.2, marginBottom: 6, textAlign: 'center' },
  chartCard: { borderRadius: 24, padding: 16, borderWidth: 1, marginTop: 12 },
  modalInputMultilineSmall: { minHeight: 96, maxHeight: 118, textAlignVertical: 'top', paddingTop: 12, paddingBottom: 12 },
  chartTitle: { fontSize: 15, fontWeight: '800', textAlign: 'center', marginBottom: 12, letterSpacing: -0.2 },
  emptyChart: { borderRadius: 16, padding: 16, alignItems: 'center', justifyContent: 'center' },
  emptyChartText: { fontSize: 12, fontWeight: '600', textAlign: 'center' },
  manageCard: { borderRadius: 24, padding: 16, borderWidth: 1, marginTop: 12 },
  manageHeader: { marginBottom: 8 },
  manageHeaderRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8, marginBottom: 10 },
  manageTitle: { fontSize: 16, fontWeight: '800', flexShrink: 1, letterSpacing: -0.2 },
  manageSub: { fontSize: 12, fontWeight: '500', marginTop: 3 },
  fullRowCard: { position: 'relative', overflow: 'hidden', borderRadius: 18, paddingVertical: 14, paddingHorizontal: 14, borderWidth: 1, marginTop: 10, width: '100%' },
  rowItemTitle: { fontSize: 14, fontWeight: '700', lineHeight: 19, letterSpacing: -0.2 },
  rowItemMeta: { fontSize: 11, fontWeight: '500', marginTop: 3 },
  linkListWrap: { marginTop: 6, gap: 6 },
  linkChip: { alignSelf: 'flex-start', maxWidth: '100%', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: 'rgba(212,170,76,0.12)', borderWidth: 1 },
  linkChipText: { fontSize: 11, fontWeight: '800' },
  modalCardLinkConfirm: { alignItems: 'center', justifyContent: 'center' },
  linkConfirmIconWrap: { width: 52, height: 52, borderRadius: 18, borderWidth: 1, alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
  linkConfirmIcon: { fontSize: 24, fontWeight: '900' },
  linkPreviewCard: { width: '100%', borderRadius: 18, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 12, marginBottom: 2 },
  linkPreviewText: { fontSize: 12, fontWeight: '800', textAlign: 'center' },
  modalCardUpdateNotice: { alignItems: 'center', justifyContent: 'center' },
  updateNoticeIconWrap: { width: 58, height: 58, borderRadius: 24, borderWidth: 1, alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  updateNoticeIcon: { fontSize: 26, fontWeight: '900' },
  inlineActions: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'nowrap', justifyContent: 'center', maxWidth: '62%' },
  categoryToolbar: { flexDirection: 'row', gap: 8, flexWrap: 'wrap', alignItems: 'center' },
  smallActionBtn: { minHeight: 38, minWidth: 38, paddingHorizontal: 12, borderRadius: 14, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
  smallActionBtnText: { fontSize: 11, fontWeight: '800' },
  filterRow: { gap: 8, paddingRight: 10 },
  filterPill: { minHeight: 38, paddingHorizontal: 16, borderRadius: 999, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
  filterPillText: { fontSize: 12, fontWeight: '700', letterSpacing: 0.1 },
  sectionCardSpaced: { marginTop: 12 },
  quickActionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  quickActionBtn: { width: '47%', minHeight: 54, borderRadius: 18, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  quickActionBtnText: { fontSize: 14, fontWeight: '800', letterSpacing: -0.2 },
  dateInputRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  dateInputField: { flex: 1, minWidth: 0 },
  calendarBtn: { width: 42, minHeight: 46, borderRadius: 16, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  calendarBtnText: { fontSize: 18 },
  calendarSection: { marginBottom: 10 },
  calendarDaysGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, justifyContent: 'center' },
  calendarDayBtn: { width: '14%', minWidth: 40, minHeight: 40, borderRadius: 14, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  calendarDayText: { fontSize: 12, fontWeight: '800' },
  bottomBar: { position: 'absolute', left: 14, right: 14, minHeight: 68, borderRadius: 34, borderWidth: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 14, paddingTop: 6, paddingBottom: 6, shadowOpacity: 0.16, shadowRadius: 32, shadowOffset: { width: 0, height: 12 }, elevation: 12 },
  bottomHalf: { flex: 1, flexDirection: 'row', justifyContent: 'space-evenly', alignItems: 'center', gap: 2, paddingBottom: 0, paddingHorizontal: 2 },
  plusButton: { width: 58, height: 58, marginHorizontal: 10, borderRadius: 999, alignItems: 'center', justifyContent: 'center', marginTop: 0, alignSelf: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.16)', shadowOpacity: 0.22, shadowRadius: 20, shadowOffset: { width: 0, height: 8 }, elevation: 10 },
  syncBadge: { position: 'absolute', right: 18, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, borderWidth: 1 },
  syncBadgeText: { fontSize: 12, fontWeight: '800' },
  modalCard: { width: '86%', maxWidth: 430, maxHeight: '94%', alignSelf: 'center', borderRadius: 30, paddingHorizontal: 20, paddingTop: 22, paddingBottom: 30, borderWidth: 1, overflow: 'hidden', shadowColor: '#000000', shadowOpacity: 0.24, shadowRadius: 36, shadowOffset: { width: 0, height: 18 }, elevation: 18 },
  modalCardConfirmDelete: { width: '78%', maxWidth: 360, minHeight: 180, paddingBottom: 20 },
  modalCardCartaoCompra: { paddingBottom: 36, minHeight: 430 },
  modalQuickActions: { paddingBottom: 26 },
  modalTitle: { fontSize: 19, fontWeight: '800', textAlign: 'center', marginBottom: 18, letterSpacing: -0.4 },
  modalField: { marginBottom: 14 },
  modalLabel: { fontSize: 11, fontWeight: '700', marginBottom: 7, textTransform: 'uppercase', letterSpacing: 1.1 },
  modalInput: { minHeight: 50, borderWidth: 1, borderRadius: 16, paddingHorizontal: 16, fontSize: 15, fontWeight: '600' },
  modalInputMultiline: { minHeight: 120, maxHeight: 140, textAlignVertical: 'top', paddingTop: 12, paddingBottom: 12 },
  dualFieldLabel: { textAlign: 'center' },
  totalParcelasField: { alignItems: 'center' },
  totalParcelasFieldWide: { alignItems: 'stretch' },
  totalParcelasInput: { width: '48%', minWidth: 120, textAlign: 'center' },
  totalParcelasInputWide: { width: '100%', minWidth: 0 },
  modalActions: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, marginTop: 12, width: '100%' },
  modalActionBtn: { flex: 1, minHeight: 48, paddingHorizontal: 16, borderRadius: 16, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  modalActionText: { fontSize: 14, fontWeight: '800', letterSpacing: -0.2 },
  modalScroll: {
    width: '100%',
  },

  modalScrollContent: {
    paddingBottom: 4,
    flexGrow: 1,
  },

  modalContentFill: { flex: 1 },
  modalScrollContentWithFooter: { paddingBottom: 26 },
  modalCardWithFixedFooter: { overflow: 'hidden' },
  modalActionsSticky: { borderTopWidth: 1, paddingTop: 1, paddingHorizontal: 2, paddingBottom: 10 },
  searchHighlightCard: { overflow: 'visible' },
  searchHighlightOverlay: { position: 'absolute', top: -1, right: -1, bottom: -1, left: -1, borderWidth: 2, borderRadius: 18, opacity: 0, backgroundColor: 'transparent' },

  modalCardSettings: {
    paddingBottom: 24,
    minHeight: Platform.OS === 'web' ? 0 : 520,
    maxHeight: '86%',
  },
  modalSettingsScroll: {
    flex: 1,
    width: '100%',
    minHeight: 0,
  },
  settingsSectionTitle: { fontSize: 12, fontWeight: '800', marginBottom: 10, textTransform: 'uppercase', letterSpacing: 1.2 },
  settingsCard: { position: 'relative', overflow: 'hidden', borderWidth: 1, borderRadius: 20, padding: 16, marginTop: 12 },
  avatarImage: { width: '100%', height: '100%', borderRadius: 999 },
  modalCardExportPreview: { width: '90%', maxWidth: 560, minHeight: 460, maxHeight: '86%', paddingBottom: 0 },
  exportPreviewBodyWrap: { flexGrow: 1 },
  exportPreviewPdfWrap: { minHeight: 420, height: 420, marginBottom: 0 },
  exportPreviewPdfCard: { flex: 1, borderWidth: 1, borderRadius: 20, overflow: 'hidden' },
  exportPreviewPdfNative: { flex: 1, width: '100%' },

  modalCardPremiumLock: { width: '84%', maxWidth: 390, minHeight: 258, paddingBottom: 35 },
  modalTitleCentered: { textAlign: 'center' },
  premiumLockGlow: {
    alignSelf: 'center',
    width: 56,
    height: 56,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
    shadowColor: '#000000',
    shadowOpacity: 0.086,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  premiumLockGlowText: { fontSize: 24, fontWeight: '900', color: '#C89B2C' },
  premiumLockDescription: { fontSize: 14, fontWeight: '700', lineHeight: 20, textAlign: 'center', marginBottom: 14 },
  premiumLockInfoCard: { borderWidth: 1, borderRadius: 18, padding: 12, marginBottom: 14 },
  premiumLockInfoTitle: { fontSize: 12, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 6, textAlign: 'center' },
  premiumLockInfoText: { fontSize: 13, fontWeight: '700', lineHeight: 18, textAlign: 'center' },
})
