// Estilos compartilhados da tela home e das abas.
// Extraido do home.tsx para que os componentes de aba (FixoTab, VariavelTab,
// CartaoTab) usem exatamente as mesmas definicoes, sem duplicacao.

import { Platform, StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  sectionSpacer: { height: 14 },
  sectionSpacerLarge: { height: 22 },
  safeArea: { flex: 1 },
  loadingWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12, padding: 24 },
  loadingText: { fontSize: 16, fontWeight: '700' },
  scrollContent: { paddingHorizontal: 16, paddingTop: 14 },
  topRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 },
  homePremiumBadgeWrap: {
    alignSelf: 'flex-start',
    minHeight: 36,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginBottom: 12,
  },

  homePremiumBadgeText: {
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.2,
  },

  topActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  avatar: { width: 48, height: 48, borderRadius: 999, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5 },
  avatarText: { fontSize: 17, fontWeight: '800', letterSpacing: 0.3 },
  themeButton: { width: 42, height: 42, borderRadius: 999, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
  valueToggleButton: { marginLeft: -2 },
  themeButtonText: { fontSize: 17, fontWeight: '900', lineHeight: 17 },
  logoutButton: { minHeight: 42, paddingHorizontal: 16, borderRadius: 999, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
  logoutButtonText: { fontSize: 13, fontWeight: '700', letterSpacing: 0.2 },
  eyebrow: { fontSize: 11, fontWeight: '800', letterSpacing: 1.4, textTransform: 'uppercase', marginBottom: 8, textAlign: 'center' },
  title: { fontSize: 27, fontWeight: '800', textAlign: 'center', letterSpacing: -0.6 },
  subtitle: { fontSize: 13, lineHeight: 19, textAlign: 'center', marginTop: 5, marginBottom: 16, fontWeight: '500' },
  brandHeroCard: { position: 'relative', overflow: 'hidden', flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 24, paddingLeft: 14, paddingRight: 14, paddingVertical: 12, borderWidth: 1, marginBottom: 12, shadowOpacity: 0.086, shadowRadius: 27, shadowOffset: { width: 0, height: 8 }, elevation: 5 },
  brandHeroAccentLine: { position: 'absolute', left: 0, top: 8, bottom: 8, width: 4, borderRadius: 999 },
  brandHeroIconShell: { width: 62, height: 62, borderRadius: 22, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
  brandHeroIcon: { width: 44, height: 44 },
  brandHeroTextWrap: { flex: 1, justifyContent: 'center' },
  brandHeroBadge: { alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 999, borderWidth: 1, marginBottom: 6 },
  brandHeroEyebrow: { fontSize: 9, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1.1 },
  brandHeroTitle: { fontSize: 16, fontWeight: '900', marginBottom: 3 },
  brandHeroSub: { fontSize: 12, fontWeight: '700', lineHeight: 16, maxWidth: '94%' },
  selectorGroup: { flexDirection: 'row', gap: 10, marginBottom: 12 },
  dropdownButton: { flex: 1, minHeight: 62, borderRadius: 20, paddingHorizontal: 14, paddingVertical: 10, borderWidth: 1, justifyContent: 'center' },
  dropdownLabel: { fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1.2, marginBottom: 4, textAlign: 'center' },
  dropdownValueRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  dropdownValue: { fontSize: 16, fontWeight: '800', textAlign: 'center', letterSpacing: -0.3 },
  dropdownIcon: { fontSize: 15, fontWeight: '900', marginTop: -2 },
  salaryCard: { borderRadius: 24, padding: 18, borderWidth: 1, marginBottom: 10 },
  cardLabelCentered: { fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1.3, marginBottom: 10, textAlign: 'center' },
  salaryRowCentered: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  salaryValueCentered: { fontSize: 30, fontWeight: '800', textAlign: 'center', letterSpacing: -1 },
  salaryInput: { minWidth: 180, fontSize: 29, fontWeight: '800', textAlign: 'center', paddingVertical: 0, letterSpacing: -1 },
  salaryEditButton: { width: 34, height: 34, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
  salaryEditText: { fontSize: 16, fontWeight: '800' },
  balanceCard: { borderRadius: 26, padding: 20, borderWidth: 1, marginBottom: 10, shadowOpacity: 0.10, shadowRadius: 24, shadowOffset: { width: 0, height: 10 }, elevation: 5 },
  balanceValueCentered: { fontSize: 34, fontWeight: '800', textAlign: 'center', letterSpacing: -1.2 },
  summaryRow: { flexDirection: 'row', gap: 10, marginBottom: 18 },
  summaryCard: { flex: 1, minWidth: '47%', borderRadius: 20, padding: 14, borderWidth: 1 },
  smallLabel: { fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1.2, marginBottom: 6, textAlign: 'center' },
  smallValue: { fontSize: 17, fontWeight: '800', textAlign: 'center', letterSpacing: -0.4 },
  chartCard: { borderRadius: 24, padding: 16, borderWidth: 1, marginTop: 18 },
  investmentCard: { borderRadius: 26, padding: 18, borderWidth: 1, marginTop: 18, shadowOpacity: 0.08, shadowRadius: 24, shadowOffset: { width: 0, height: 10 }, elevation: 4 },
  investmentHeaderRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginBottom: 14 },
  investmentEyebrow: { fontSize: 11, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1.1, marginBottom: 6 },
  investmentTitle: { fontSize: 19, fontWeight: '800', letterSpacing: -0.4 },
  investmentSub: { marginTop: 4, fontSize: 13, lineHeight: 18, fontWeight: '700' },
  investmentBadge: { minWidth: 72, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12, paddingVertical: 10, borderRadius: 18, borderWidth: 1 },
  investmentBadgeText: { fontSize: 18, fontWeight: '900' },
  investmentBaseRow: { flexDirection: 'row', gap: 10, marginBottom: 14 },
  investmentBaseChip: { flex: 1, minHeight: 44, borderRadius: 18, borderWidth: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10 },
  investmentBaseChipText: { fontSize: 13, fontWeight: '800', textAlign: 'center' },
  investmentHighlightCard: { borderRadius: 22, borderWidth: 1, padding: 14, marginBottom: 14 },
  investmentHighlightTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 },
  investmentHighlightLabel: { fontSize: 12, fontWeight: '700', marginBottom: 4 },
  investmentHighlightValue: { fontSize: 26, fontWeight: '800', letterSpacing: -0.8 },
  investmentMiniLabel: { fontSize: 11, fontWeight: '700', marginBottom: 4 },
  investmentMiniValue: { fontSize: 14, fontWeight: '800' },
  investmentHelperText: { marginTop: 10, fontSize: 12, lineHeight: 17, fontWeight: '600' },
  investmentSliderBlock: { marginTop: 2 },
  investmentSliderHeader: { flexDirection: 'row', justifyContent: 'flex-start', alignItems: 'center', marginBottom: 10 },
  investmentSliderLabel: { fontSize: 14, fontWeight: '800' },
  investmentSliderValue: { fontSize: 16, fontWeight: '900' },
  investmentSliderMetaRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8, paddingHorizontal: 2 },
  investmentSliderMetaText: { fontSize: 11, fontWeight: '800' },
  investmentTrackOuter: { position: 'relative', borderWidth: 1, borderRadius: 24, minHeight: 64, justifyContent: 'center', paddingHorizontal: 14, marginTop: 2 },
  investmentTrackBar: { height: 8, borderRadius: 999 },
  investmentTrackFill: { position: 'absolute', left: 14, top: '50%', marginTop: -4, height: 8, borderRadius: 999 },
  investmentTrackTick: { position: 'absolute', top: 20, width: 2, height: 24, marginLeft: -1, borderRadius: 999, opacity: 0.6 },
  investmentKnob: { position: 'absolute', top: '50%', marginTop: -14, marginLeft: -14, width: 28, height: 28, borderRadius: 999, borderWidth: 2, alignItems: 'center', justifyContent: 'center', shadowOpacity: 0.101, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 5 },
  investmentKnobInner: { width: 10, height: 10, borderRadius: 999 },
  investmentSliderScale: { flexDirection: 'row', justifyContent: 'space-between', gap: 8, marginTop: 12, flexWrap: 'wrap' },
  investmentScalePill: { minWidth: 46, paddingHorizontal: 10, minHeight: 34, borderRadius: 999, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  investmentScalePillText: { fontSize: 11, fontWeight: '800' },
  investmentManualField: { marginTop: 10, width: '44%', minWidth: 140, maxWidth: 175, alignSelf: 'flex-start' },
  investmentManualInput: { flex: 1, textAlign: 'center', fontSize: 15, fontWeight: '800' },
  investmentManualInputRow: { flexDirection: 'row', alignItems: 'center', width: '100%', gap: 8 },
  investmentManualSuffix: { fontSize: 16, fontWeight: '900' },
  modalInputMultilineSmall: { minHeight: 96, maxHeight: 118, textAlignVertical: 'top', paddingTop: 12, paddingBottom: 12 },
  chartTitle: { fontSize: 15, fontWeight: '800', textAlign: 'center', marginBottom: 12, letterSpacing: -0.2 },
  chartContentRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  pieWrapSide: { width: 140, height: 140, alignItems: 'center', justifyContent: 'center' },
  emptyChart: { borderRadius: 16, padding: 16, alignItems: 'center', justifyContent: 'center' },
  emptyChartText: { fontSize: 12, fontWeight: '600', textAlign: 'center' },
  pieCenterLabel: { position: 'absolute', alignItems: 'center', justifyContent: 'center' },
  pieCenterSmall: { fontSize: 10, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 2 },
  pieCenterValue: { fontSize: 11, fontWeight: '900', textAlign: 'center', paddingHorizontal: 20 },
  legendSideList: { flex: 1, gap: 6 },
  legendSideItem: { borderRadius: 16, borderWidth: 1, paddingVertical: 10, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  legendSideTop: { flexDirection: 'row', alignItems: 'center', gap: 6, flex: 1, minWidth: 0 },
  legendDot: { width: 10, height: 10, borderRadius: 999 },
  legendCategory: { fontSize: 12, fontWeight: '800', flex: 1 },
  legendPercentInline: { fontSize: 11, fontWeight: '700', marginHorizontal: 6 },
  legendValueInline: { fontSize: 11, fontWeight: '900', maxWidth: 88, textAlign: 'right' },
  manageCard: { borderRadius: 24, padding: 16, borderWidth: 1, marginTop: 18 },
  manageHeader: { marginBottom: 8 },
  manageHeaderRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8, marginBottom: 10 },
  manageTitle: { fontSize: 16, fontWeight: '800', flexShrink: 1, letterSpacing: -0.2 },
  manageSub: { fontSize: 12, fontWeight: '500', marginTop: 3 },
  sectionBlockTitle: { fontSize: 15, fontWeight: '800', marginBottom: 12, letterSpacing: -0.2 },
  fullRowCard: { position: 'relative', overflow: 'hidden', borderRadius: 18, paddingVertical: 14, paddingHorizontal: 14, borderWidth: 1, marginTop: 10, width: '100%' },
  fullRowTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  fullRowTitleWrap: { flex: 1, minWidth: 0 },
  rowItemTitle: { fontSize: 15, fontWeight: '700', lineHeight: 20, letterSpacing: -0.2 },
  rowItemMeta: { fontSize: 12, fontWeight: '500', marginTop: 4 },
  linkListWrap: { marginTop: 6, gap: 6 },
  linkChip: { alignSelf: 'flex-start', maxWidth: '100%', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: 'rgba(212,170,76,0.12)', borderWidth: 1 },
  linkChipText: { fontSize: 11, fontWeight: '800' },
  linkFieldHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
  linkInputRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 8 },
  linkInputField: { flex: 1, minHeight: 44 },
  linkAddBtn: { minWidth: 30, minHeight: 30, paddingHorizontal: 0, borderRadius: 12 },
  linkRemoveBtn: { width: 34, height: 34, borderRadius: 12, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  linkRemoveBtnText: { fontSize: 18, fontWeight: '900', lineHeight: 18 },
  modalCardLinkConfirm: { alignItems: 'center', justifyContent: 'center' },
  linkConfirmIconWrap: { width: 52, height: 52, borderRadius: 18, borderWidth: 1, alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
  linkConfirmIcon: { fontSize: 24, fontWeight: '900' },
  linkPreviewCard: { width: '100%', borderRadius: 18, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 12, marginBottom: 2 },
  linkPreviewText: { fontSize: 12, fontWeight: '800', textAlign: 'center' },
  modalCardUpdateNotice: { alignItems: 'center', justifyContent: 'center' },
  updateNoticeIconWrap: { width: 58, height: 58, borderRadius: 24, borderWidth: 1, alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  updateNoticeIcon: { fontSize: 26, fontWeight: '900' },
  rowItemValue: { fontSize: 15, fontWeight: '800', letterSpacing: -0.3 },
  inlineActions: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'nowrap', justifyContent: 'center', maxWidth: '62%' },
  statusBtn: { minHeight: 30, paddingHorizontal: 12, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
  statusBtnText: { fontSize: 10, fontWeight: '800', color: '#ffffff', letterSpacing: 0.4 },
  iconBtn: { width: 32, height: 32, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
  iconBtnText: { fontSize: 18, fontWeight: '900', lineHeight: 18 },
  categoryToolbar: { flexDirection: 'row', gap: 8, flexWrap: 'wrap', alignItems: 'center' },
  smallActionBtn: { minHeight: 38, minWidth: 38, paddingHorizontal: 12, borderRadius: 14, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
  smallActionBtnText: { fontSize: 11, fontWeight: '800' },
  smallActionBtnIcon: { fontSize: 14, fontWeight: '900' },
  filterRow: { gap: 8, paddingRight: 10 },
  filterPill: { minHeight: 38, paddingHorizontal: 16, borderRadius: 999, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
  filterPillText: { fontSize: 12, fontWeight: '700', letterSpacing: 0.1 },
  variableSwitchRow: { flexDirection: 'row', gap: 8, marginTop: 2, marginBottom: 12 },
  variableSwitchBtn: { flex: 1, minHeight: 46, borderRadius: 16, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  variableSwitchBtnText: { fontSize: 13, fontWeight: '800', letterSpacing: -0.1 },
  sectionCardSpaced: { marginTop: 18 },
  quickActionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  quickActionBtn: { width: '47%', minHeight: 54, borderRadius: 18, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  quickActionBtnText: { fontSize: 14, fontWeight: '800', letterSpacing: -0.2 },
  dateInputRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  dateInputField: { flex: 1, minWidth: 0 },
  calendarBtn: { width: 42, minHeight: 46, borderRadius: 16, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  calendarBtnText: { fontSize: 18 },
  modalCardCalendar: { paddingBottom: 45, minHeight: 470 },
  calendarSection: { marginBottom: 10 },
  calendarDaysGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, justifyContent: 'center' },
  calendarDayBtn: { width: '14%', minWidth: 40, minHeight: 40, borderRadius: 14, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  calendarDayText: { fontSize: 12, fontWeight: '800' },
  bottomBar: { position: 'absolute', left: 14, right: 14, minHeight: 68, borderRadius: 34, borderWidth: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 14, paddingTop: 6, paddingBottom: 6, shadowOpacity: 0.16, shadowRadius: 32, shadowOffset: { width: 0, height: 12 }, elevation: 12 },
  bottomHalf: { flex: 1, flexDirection: 'row', justifyContent: 'space-evenly', alignItems: 'center', gap: 4, paddingBottom: 0 },
  bottomDivider: { width: 1, height: 20, borderRadius: 999, opacity: 0.9 },
  bottomItem: { flex: 1, alignItems: 'center', justifyContent: 'center', minWidth: 0 },
  bottomItemText: { fontSize: 11, fontWeight: '800', lineHeight: 15, textTransform: 'uppercase', letterSpacing: 0.9 },
  plusButton: { width: 58, height: 58, borderRadius: 999, alignItems: 'center', justifyContent: 'center', marginTop: 0, alignSelf: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.16)', shadowOpacity: 0.22, shadowRadius: 20, shadowOffset: { width: 0, height: 8 }, elevation: 10 },
  plusButtonText: { fontSize: 25, fontWeight: '700', lineHeight: 26, marginTop: -1 },
  syncBadge: { position: 'absolute', right: 18, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, borderWidth: 1 },
  syncBadgeText: { fontSize: 12, fontWeight: '800' },
  modalCard: { width: '86%', maxWidth: 430, maxHeight: '94%', alignSelf: 'center', borderRadius: 30, paddingHorizontal: 20, paddingTop: 22, paddingBottom: 30, borderWidth: 1, overflow: 'hidden', shadowColor: '#000000', shadowOpacity: 0.24, shadowRadius: 36, shadowOffset: { width: 0, height: 18 }, elevation: 18 },
  modalCardExtraBottom: { paddingBottom: 36 },
  modalCardExtraTall: { paddingBottom: 40 },
  modalCardNotesFixedFooter: { width: '88%', maxWidth: 440, minHeight: 430, maxHeight: '86%', paddingBottom: 0 },
  modalCardYear: { paddingBottom: 34 },
  modalCardScrollHint: { paddingBottom: 30 },
  modalCardConfirmDelete: { width: '78%', maxWidth: 360, minHeight: 180, paddingBottom: 20 },
  modalCardGoal: { paddingBottom: 40, minHeight: 270 },
  modalCardLancamentoEntrada: { paddingBottom: 0, minHeight: 378, maxHeight: '86%' },
  modalCardEditEntrada: { paddingBottom: 0, minHeight: 330, maxHeight: '86%' },
  modalCardEditFixo: { paddingBottom: 35, minHeight: 330 },
  modalCardEditSaida: { paddingBottom: 0, minHeight: 440, maxHeight: '86%' },
  modalCardLancamentoSaida: { paddingBottom: 0, minHeight: 470, maxHeight: '86%' },
  modalCardLancamentoSaidaKeyboard: { paddingBottom: 0, minHeight: 336, maxHeight: '68%' },
  modalCardManageCards: { paddingBottom: 24, minHeight: 360 },
  modalCardNewCard: { paddingBottom: 30, minHeight: 225 },
  modalCardNewCategory: { paddingBottom: 20, minHeight: 204 },
  modalCardLancamentoParcela: { paddingBottom: 0, minHeight: 500, maxHeight: '86%' },
  modalCardLancamentoParcelaKeyboard: { paddingBottom: 0, minHeight: 336, maxHeight: '68%' },
  modalCardCartaoCompra: { paddingBottom: 36, minHeight: 430 },
  modalQuickActions: { paddingBottom: 26 },
  modalTitle: { fontSize: 19, fontWeight: '800', textAlign: 'center', marginBottom: 18, letterSpacing: -0.4 },
  modalHintWrap: { alignSelf: 'center', minHeight: 28, borderRadius: 999, paddingHorizontal: 12, marginBottom: 10, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  modalOption: { minHeight: 44, borderRadius: 16, borderWidth: 1, alignItems: 'center', justifyContent: 'center', marginBottom: 8, paddingHorizontal: 14 },
  modalOptionText: { fontSize: 15, fontWeight: '700', letterSpacing: -0.2 },
  monthModalScroll: { maxHeight: 340 },
  switchRow: { flexDirection: 'row', gap: 8, marginBottom: 10 },
  switchRowThree: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 10 },
  switchBtnThree: { width: '48%', minHeight: 42, borderRadius: 14, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  switchBtn: { flex: 1, minHeight: 46, borderRadius: 14, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  switchBtnText: { fontSize: 13, fontWeight: '800', letterSpacing: -0.1 },
  modalField: { marginBottom: 14 },
  modalLabel: { fontSize: 11, fontWeight: '700', marginBottom: 7, textTransform: 'uppercase', letterSpacing: 1.1 },
  modalInput: { minHeight: 50, borderWidth: 1, borderRadius: 16, paddingHorizontal: 16, fontSize: 15, fontWeight: '600' },
  modalInputMultiline: { minHeight: 120, maxHeight: 140, textAlignVertical: 'top', paddingTop: 12, paddingBottom: 12 },
  noteInputWrap: { position: 'relative' },
  noteInputWithIndicator: { paddingRight: 26 },
  noteScrollIndicatorTrack: { position: 'absolute', right: 10, top: 14, bottom: 14, width: 4, borderRadius: 999, overflow: 'hidden' },
  noteScrollIndicatorThumb: { position: 'absolute', top: 0, width: 4, height: 34, borderRadius: 999 },
  dualFieldRow: { flexDirection: 'row', gap: 12, alignItems: 'flex-start' },
  dualFieldItem: { flex: 1 },
  dualFieldLabel: { textAlign: 'center' },
  totalParcelasField: { alignItems: 'center' },
  totalParcelasFieldWide: { alignItems: 'stretch' },
  totalParcelasInput: { width: '48%', minWidth: 120, textAlign: 'center' },
  totalParcelasInputWide: { width: '100%', minWidth: 0 },
  modalHintText: { fontSize: 11, fontWeight: '700', textAlign: 'center' },
  modalActions: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, marginTop: 12, width: '100%' },
  modalActionsLower: { marginTop: 16 },
  modalActionsFixedFooter: { marginTop: 12, paddingTop: 10 },
  modalActionBtn: { flex: 1, minHeight: 48, paddingHorizontal: 16, borderRadius: 16, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  modalActionText: { fontSize: 14, fontWeight: '800', letterSpacing: -0.2 },
  categoryScroll: { maxHeight: 340 },
  categoryManageRow: { borderRadius: 16, padding: 10, borderWidth: 1, marginBottom: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  categoryManageText: { fontSize: 14, fontWeight: '800', flex: 1, marginRight: 10 },
  categoryManageActions: { flexDirection: 'row', gap: 8 },
  manageMiniBtn: { width: 36, height: 36, borderRadius: 12, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  manageMiniBtnText: { fontSize: 14, fontWeight: '900' },
  deleteCardButton: { marginTop: 12, minHeight: 42, borderRadius: 14, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  deleteCardButtonText: { fontSize: 12, fontWeight: '800' },
  compareSelectorRow: {
  flexDirection: 'row',
  alignItems: 'center',
  gap: 8,
  marginTop: 10,
},  modalContentWrap: {
    width: '100%',
  },
  modalFormScroll: { width: '100%', maxHeight: 320 },
  modalFormScrollContent: { paddingBottom: 4 },

  modalScroll: {
    width: '100%',
  },

  modalScrollContent: {
    paddingBottom: 4,
    flexGrow: 1,
  },

compareArrow: {
  width: 40,
  height: 40,
  borderRadius: 999,
  alignItems: 'center',
  justifyContent: 'center',
  borderWidth: 1,
},

compareArrowText: {
  fontSize: 24,
  fontWeight: '800',
  lineHeight: 24,
},

comparePill: {
  flex: 1,
  minHeight: 42,
  borderRadius: 16,
  alignItems: 'center',
  justifyContent: 'center',
  borderWidth: 1,
  paddingHorizontal: 10,
},

comparePillText: {
  fontSize: 14,
  fontWeight: '800',
},

comparisonGrid: {
  flexDirection: 'row',
  flexWrap: 'wrap',
  gap: 8,
},

compareMetaText: {
  fontSize: 11,
  fontWeight: '700',
  marginTop: 4,
  textAlign: 'center',
},

  compareBarTrack: {
    height: 12,
    borderRadius: 999,
    borderWidth: 1,
    overflow: 'hidden',
  },
  compareBarFill: {
    height: '100%',
    borderRadius: 999,
  },
  searchWrap: {
    marginTop: 10,
    marginBottom: 10,
  },
  modalContentFill: { flex: 1 },
  modalScrollContentWithFooter: { paddingBottom: 26 },
  modalCardWithFixedFooter: { overflow: 'hidden' },
  modalActionsSticky: { borderTopWidth: 1, paddingTop: 1, paddingHorizontal: 2, paddingBottom: 10 },
  searchHighlightCard: { overflow: 'visible' },
  searchHighlightOverlay: { position: 'absolute', top: -1, right: -1, bottom: -1, left: -1, borderWidth: 2, borderRadius: 18, opacity: 0, backgroundColor: 'transparent' },

  searchInput: { minHeight: 48, borderWidth: 1, borderRadius: 16, paddingHorizontal: 16, fontSize: 14, fontWeight: '600' },
  cardLimitPercent: {
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'right',
    marginTop: 6,
  },
  modalCardSettings: {
    paddingBottom: 24,
    minHeight: Platform.OS === 'web' ? 0 : 520,
    maxHeight: '86%',
  },
  modalSettingsScroll: {
    flex: 1,
    width: '100%',
    minHeight: 0,
  },
  settingsSectionTitle: { fontSize: 12, fontWeight: '800', marginBottom: 10, textTransform: 'uppercase', letterSpacing: 1.2 },
  settingsCard: { position: 'relative', overflow: 'hidden', borderWidth: 1, borderRadius: 20, padding: 16, marginTop: 12 },
  avatarImage: { width: '100%', height: '100%', borderRadius: 999 },
  settingsInfoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  settingsInfoPill: { width: '48%', borderWidth: 1, borderRadius: 16, paddingVertical: 12, paddingHorizontal: 10 },
  settingsInfoLabel: { fontSize: 10, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.9, marginBottom: 4, textAlign: 'center' },
  settingsInfoValue: { fontSize: 14, fontWeight: '900', textAlign: 'center' },
  settingsActionBtn: { minHeight: 46, borderWidth: 1, borderRadius: 16, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16 },
  settingsActionBtnText: { fontSize: 13, fontWeight: '900' },
  modalCardExportPreview: { width: '90%', maxWidth: 560, minHeight: 460, maxHeight: '86%', paddingBottom: 0 },
  exportPreviewBodyWrap: { flexGrow: 1 },
  exportPreviewPdfWrap: { minHeight: 420, height: 420, marginBottom: 0 },
  exportPreviewPdfCard: { flex: 1, borderWidth: 1, borderRadius: 20, overflow: 'hidden' },
  exportPreviewPdfNative: { flex: 1, width: '100%' },

  modalCardPremiumLock: { width: '84%', maxWidth: 390, minHeight: 258, paddingBottom: 35 },
  modalTitleCentered: { textAlign: 'center' },
  premiumLockGlow: {
    alignSelf: 'center',
    width: 56,
    height: 56,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
    shadowColor: '#000000',
    shadowOpacity: 0.086,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  premiumLockGlowText: { fontSize: 24, fontWeight: '900', color: '#C89B2C' },
  premiumLockDescription: { fontSize: 14, fontWeight: '700', lineHeight: 20, textAlign: 'center', marginBottom: 14 },
  premiumLockInfoCard: { borderWidth: 1, borderRadius: 18, padding: 12, marginBottom: 14 },
  premiumLockInfoTitle: { fontSize: 12, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 6, textAlign: 'center' },
  premiumLockInfoText: { fontSize: 13, fontWeight: '700', lineHeight: 18, textAlign: 'center' },
  premiumBlockerOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 80,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingBottom: 112,
    backgroundColor: 'rgba(2, 8, 6, 0.22)',
  },
  premiumBlockerCard: {
    width: '92%',
    maxWidth: 380,
    borderRadius: 24,
    borderWidth: 1,
    paddingVertical: 18,
    paddingHorizontal: 18,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.13,
    shadowRadius: 27,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  premiumBlockerEyebrow: {
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1.2,
    color: '#E8C462',
    marginBottom: 6,
  },
  premiumBlockerTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#ffffff',
    marginBottom: 6,
    textAlign: 'center',
  },
  premiumBlockerText: {
    fontSize: 13,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.88)',
    textAlign: 'center',
    lineHeight: 18,
  },
})
